export const FETCH_USER_LIST_SUCCESS = 'FETCH_USER_LIST_SUCCESS';

export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS';
export const CLEAR_USER_DETAILS_SUCCESS = 'CLEAR_USER_DETAILS_SUCCESS';

